name: Test Action Fix

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Hello Step
        run: echo "Hello from GitHub Actions!"
