name: Basic GitHub Action Test

on:
  workflow_dispatch:  # allows manual triggering

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: 23f3004446@ds.study.iitm.ac.in
        run: echo "Hello from GitHub Actions! 🎉"
